fix: unresponsiveness with long songs
aquelemiguel/parrot pull request #165
Opened 2022-03-04 19:22 UTC by aquelemiguel

Closes #88.

## Decisions

When streaming to the terminal, download progress logs were also getting piped to stdout and then being consumed by Songbird and fed to ffmpeg. Using the `-q` flag in yt-dlp disables these messages.

![image](https://user-images.githubusercontent.com/5618493/156827757-ca868b24-273b-407b-aaf1-b06a4f5e26c8.png)

2022-03-04 21:09 UTC, afonsojramos requested changes
Haven't tested yet, but I'd say that the comment is removable since `-q` is a standard flag for quiet across several CLIs and APIs.

Glad you found this stupid bug tho!!! ❤️❤️❤️❤️

2022-03-04 21:13 UTC, aquelemiguel commented
> Haven't tested yet, but I'd say that the comment is removable since `-q` is a standard flag for quiet across several CLIs and APIs.

@afonsojramos Yeah, but I found it important to state it messes with `-o -` because someone might try removing it without giving it much thought...

2022-03-05 21:34 UTC, joao-conde approved these changes

2022-03-06 22:00 UTC, merged

2022-03-06 22:03 UTC, afonsojramos commented
Just tested, doesn't work and my computer exploded.